core/webapp/node/urls.py
from django.conf.urls import patterns, url
from node import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

core/webapp/web_apps/user/urls.py
from django.conf.urls import patterns, url
from web_apps.user import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^create/$', views.create, name='create'),
    url(r'^remove/$', views.remove, name='remove'),
    url(r'^node/login/$', views.node_login, name='node_login'),
    url(r'^$', views.index, name='index'),
)

core/webapp/web_conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('web_apps.api.urls', namespace='api')),
    url(r'^agent/', include('web_apps.agent.urls', namespace='agent')),
    url(r'^task/', include('web_apps.task.urls', namespace='task')),
    url(r'^event/', include('web_apps.event.urls', namespace='event')),
    url(r'^node/', include('web_apps.node.urls', namespace='node')),
    url(r'^user/', include('web_apps.user.urls', namespace='user')),
    url(r'^chat/', include('web_apps.chat.urls', namespace='chat')),
    url(r'^dns/', include('web_apps.dns.urls', namespace='dns')),
    url(r'^', include('web_apps.home.urls', namespace='home')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/webapp/webapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^node/', include('node.urls', namespace='node')),
)

core/webapp/web_apps/user/views.py
# coding: utf-8

import json
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core import serializers
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from web_apps.chat.models import UserCluster
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.sessions.models import Session
from django.views.decorators.csrf import csrf_exempt


@login_required
def index(request):
    users = serializers.serialize('json', User.objects.all().order_by('username'))
    context = {
        'title': 'User',
        'users': users,
    }
    if request.user.is_superuser:
        context['user_creation_form'] = UserCreationForm(request.user)

    context['password_change_form'] = PasswordChangeForm(user=request.user)

    if request.META.get('HTTP_X_PJAX'):
        return render(request, 'user/content.html', context)

    return render(request, 'user/index.html', context)


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                next = request.GET.get('next', '/')
                return redirect(next)
            else:
                return redirect('user:login')
        else:
            return redirect('user:login')
    else:
        form = AuthenticationForm()
        context = {
            'title': 'Login',
            'form': form,
            'next': request.GET.get('next'),
        }

        return render(request, 'user/login.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('user:login')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            u = request.user
            password = request.POST['new_password1']
            u.set_password(password)
            u.save()
            return redirect('home:index')
        else:
            return redirect('home:index')


@login_required
@user_passes_test(lambda u: u.is_superuser)
def create(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password1']
            user = User.objects.create_user(username, '', password)
            user.save()
            redirect('user:create')

        return redirect('user:index')


@csrf_exempt
def node_login(request):
    # Get User from sessionid
    session = Session.objects.get(session_key=request.POST.get('sessionid'))
    user_id = session.get_decoded().get('_auth_user_id')
    user = User.objects.get(id=user_id)
    user_clusters = UserCluster.objects.all().filter(user=user).select_related()
    tmp_user_clusters = []
    for user_cluster in user_clusters:
        tmp_user_clusters.append({
            'cluster_name': user_cluster.cluster.cluster_name,
            'unread_comments_length': user_cluster.unread_comments_length,
        })

    data = json.dumps({
        'user': user.username,
        'user_clusters': tmp_user_clusters,
    })

    return HttpResponse(data)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def remove(request):
    if request.method == 'POST':
        targets = request.POST.getlist('target')
        for target in targets:
            user = User.objects.get(pk=target)
            user.delete()

        result = {
            'status': True,
        }

    else:
        result = {
            'status': True,
        }

    return HttpResponse(json.dumps(result))

core/webapp/templates/user/content.html
{% extends 'common/content.html' %}

{% block sidebar %}
<div>
    <div class="panel-group">
        <div class="panel">
            <a class="panel-heading show" href="#user-list">
                User list
            </a>
        </div>
        <div class="panel">
            <a class="panel-heading show" href="#change-password">Change Password</a>
        </div>
      {% if user.is_superuser %}
        <div class="panel">
            <a class="panel-heading show" href="#create-user">Create User</a>
        </div>
      {% endif %}
    </div>
</div>
{% endblock %}

{% block page_title %}
{% endblock %}

{% block main_content %}
    <div class="user-content" id="user-list-content">
        <h2 class="page-header">User List</h2>
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-search"></span>
                        </div>
                        <input type="text" class="form-control" id="search-input" placeholder="text">
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                {% if user.is_superuser %}
                    <input class="btn btn-default pull-right" type="button" value="Remove" onclick="apps.remove_data('{% url 'user:remove' %}')">
                {% endif %}
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="all-checkbox"></th>
                        <th>Username</th>
                        <th>Admin</th>
                    </tr>
                </thead>
                <tbody id="users-tbody">
                </tbody>
            </table>
        </div>
    </div>

    <div class="user-content" id="change-password-content">
        <h2 class="page-header">Change Password</h2>

        <form class="form-horizontal form-user" method="post" action="{% url 'user:change_password' %}">
            {% csrf_token %}
            <div class="form-group form-group-lg">
                <label for="inputOldPassword" class="col-sm-3 control-label">Old Password</label>
                <div class="col-sm-9">
                    <input type="password" id="inputPassword" class="form-control" name="{{ password_change_form.old_password.name }}" placeholder="Old Password" required autofocus>
                </div>
            </div>
            <div class="form-group form-group-lg">
                <label for="inputNewPassword" class="col-sm-3 control-label">New Password</label>
                <div class="col-sm-9">
                    <input type="password" id="inputPassword" class="form-control" name="{{ password_change_form.new_password1.name }}" placeholder="New Password" required>
                </div>
            </div>
            <div class="form-group form-group-lg">
                <label for="inputNewPassword2" class="col-sm-3 control-label">New Password</label>
                <div class="col-sm-9">
                    <input type="password" id="inputPassword2" class="form-control" name="{{ password_change_form.new_password2.name }}" placeholder="New Password (Confirm)" required>
                </div>
            </div>
            <div class="form-group form-group-lg">
                <div class="col-sm-offset-3 col-sm-9">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Change</button>
                </div>
            </div>
        </form>
    </div>

    <div class="user-content" id="create-user-content">
      {% if user.is_superuser %}
        <h2 class="page-header">Create User</h2>
        <form class="form-horizontal form-user" method="post" action="{% url 'user:create' %}">
            {% csrf_token %}
            <div class="form-group form-group-lg">
                <label for="inputUsername" class="col-sm-3 control-label">Username</label>
                <div class="col-sm-9">
                    <input type="text" id="inputUsername" class="form-control" name="{{ user_creation_form.username.name }}" placeholder="Username" required autofocus>
                </div>
            </div>
            <div class="form-group form-group-lg">
                <label for="inputNewPassword" class="col-sm-3 control-label">New Password</label>
                <div class="col-sm-9">
                    <input type="password" id="inputPassword" class="form-control" name="{{ user_creation_form.password1.name }}" placeholder="Password" required>
                </div>
            </div>
            <div class="form-group form-group-lg">
                <label for="inputNewPassword2" class="col-sm-3 control-label">New Password</label>
                <div class="col-sm-9">
                    <input type="password" id="inputPassword2" class="form-control" name="{{ user_creation_form.password2.name }}" placeholder="Password (Confirm)" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Create User</button>
                </div>
            </div>
        </form>
      {% endif %}
    </div>
</div> <!-- /container -->

<script type="application/json" id="users">{{ users|safe }}</script>
{% endblock %}

core/webapp/templates/user/index.html
{% extends "common/base.html" %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
    {% include 'user/content.html' %}
{% endblock content %}

core/webapp/templates/user/login.html
{% extends "common/base.html" %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<div class="container">
    <form class="form-signin form-horizontal" method="post" action="{% url 'user:login' %}">
        {% csrf_token %}
        <h2 class="page-header">Please sign in</h2>
        <div class="form-group form-group-lg">
            <label for="inputUsername" class="col-sm-3 control-label">Username</label>
            <div class="col-sm-9">
                <input id="inputUsername" class="form-control" name="{{ form.username.name }}" placeholder="Username" required autofocus>
            </div>
        </div>
        <div class="form-group form-group-lg">
            <label for="inputPassword" class="col-sm-3 control-label">Password</label>
            <div class="col-sm-9">
                <input type="password" id="inputPassword" class="form-control" name="{{ form.password.name }}" placeholder="Password" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <input class="btn btn-lg btn-block btn-primary" type="submit" value="Sign in">
                <input type="hidden" name="next" value="{{ next }}">
            </div>
        </div>
    </form>

</div> <!-- /container -->
{% endblock %}