core/webapp/node/urls.py
from django.conf.urls import patterns, url
from node import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

core/webapp/web_apps/user/urls.py
from django.conf.urls import patterns, url
from web_apps.user import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^create/$', views.create, name='create'),
    url(r'^remove/$', views.remove, name='remove'),
    url(r'^node/login/$', views.node_login, name='node_login'),
    url(r'^$', views.index, name='index'),
)

core/webapp/web_conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('web_apps.api.urls', namespace='api')),
    url(r'^agent/', include('web_apps.agent.urls', namespace='agent')),
    url(r'^task/', include('web_apps.task.urls', namespace='task')),
    url(r'^event/', include('web_apps.event.urls', namespace='event')),
    url(r'^node/', include('web_apps.node.urls', namespace='node')),
    url(r'^user/', include('web_apps.user.urls', namespace='user')),
    url(r'^chat/', include('web_apps.chat.urls', namespace='chat')),
    url(r'^dns/', include('web_apps.dns.urls', namespace='dns')),
    url(r'^', include('web_apps.home.urls', namespace='home')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/webapp/webapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^node/', include('node.urls', namespace='node')),
)

core/webapp/templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>{% block title %}FabKit{% endblock %}</title>

    <link href="{% static 'vendor/bootstrap-3.3.1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/highlight/styles/default.css' %}" rel="stylesheet">
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">FabKit</a>
                <a class="navbar-brand visible-xs" data-toggle="offcanvas" href="#">
                    <span class="glyphicon glyphicon-th-list"></span>
                    Nav
                </a>
                <a class="navbar-brand" href="#">
                    <span class="glyphicon glyphicon-chevron-up"></span>
                    Top
                </a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
              {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-left">
                    <li class="{% if namespace == 'node' %}active{% endif %}">
                        <a class="pjax" href="{% url 'node:index' %}">Node</a></li>
                    <li class="{% if namespace == 'agent' %}active{% endif %}">
                        <a class="pjax" href="{% url 'agent:index' %}">Agent</a></li>
                    <li class="{% if namespace == 'task' %}active{% endif %}">
                        <a class="pjax" href="{% url 'task:index' %}">Task</a></li>
                    <li class="{% if namespace == 'event' %}active{% endif %}">
                        <a class="pjax" href="{% url 'event:index' %}">Event</a></li>
                    <li class="{% if namespace == 'chat' %}active{% endif %}">
                        <a class="pjax" href="{% url 'chat:index' %}">Chat</a></li>
                    <li class="{% if namespace == 'dns' %}active{% endif %}">
                        <a class="pjax" href="{% url 'dns:index' %}">DNS</a></li>
                    <li class="{% if namespace == 'user' %}active{% endif %}">
                        <a class="pjax" href="{% url 'user:index' %}">User</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="glyphicon glyphicon-user" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            {{ user }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'user:logout' %}">Logout</a></li>
                            <li><a class="pjax" href="{% url 'user:index' %}#change-password">Change Password</a></li>
                        </ul>
                    </li>
                </ul>
              {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a target="blank" href="https://github.com/syunkitada/fabkit/wiki">Github</a></li>
                </ul>
              {% endif %}
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row row-offcanvas row-offcanvas-left content" id="pjax-container">
            {% block content %}
            {% endblock %}
        </div><!--/row-->
    </div>

    <footer class="container-fluid">
        <ul class="footer-links">
            <li><a target="blank" href="https://github.com/fabrickit/fabkit/blob/master/LICENSE">License (MIT)</a></li>
            <li><a target="blank" href="https://github.com/fabrickit/fabkit">Github</a></li>
            <li><a target="blank" href="https://github.com/fabrickit/fabkit/wiki">Docs</a></li>
        </ul>
    </footer>

    {% include 'modal/remove.html' %}
    {% include 'modal/datamap.html' %}

    <script src="{% static 'vendor/js/plotly-1.24.2.min.js' %}"></script>
    <script src="{% static 'vendor/js/chart-2.5.0.min.js' %}"></script>
    <script src="{% static 'vendor/js/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'vendor/js/jquery.pjax.js' %}"></script>
    <script src="{% static 'vendor/js/marked.js' %}"></script>
    <script src="{% static 'vendor/highlight/highlight.pack.js' %}"></script>
    <script src="{% static 'vendor/tablesorter/jquery.tablesorter.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-3.3.1-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/js/d3.min.js' %}"></script>

    <script src="{{ livereload_js }}"></script>
    <script src="{{ chat_socketio_js }}"></script>

    <script>
    var apps = {};  // for global namespace
    apps.debug = {{ debug|lower }};
    var chat_connection = "{{ web_hostname }}:{{ chat_port }}";
    </script>

    <script src="{% static 'js/common.js' %}"></script>

    <script>
    $(document).ready(function() {
      apps.init();

      $('[data-toggle="offcanvas"]').click(function () {
        $('.row-offcanvas').toggleClass('active');
          return false;
      });

    });
    </script>

    {% block js_extention %}{% endblock %}
</body>
</html>

core/webapp/templates/common/content.html
<title>{{ title }}</title>

<div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="navigation" id="sidebar-wrapper-wrapper">
    <div class="sidebar-wrapper col-xs-6 col-sm-3">
        <div class="sidebar" id="sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>

<div class="col-xs-12 col-sm-9 col-sm-offset-3 main" id="main-content-wrapper-wrapper">
    <div class="row main-content-wrapper">
        <div class="main-content">
          {% block page_title %}
            <h2 class="page-header">{{ title }}</h2>
          {% endblock %}
            {% block main_content %}{% endblock %}
        </div>
    </div>
</div>

<script type="application/json" id="agent_cluster">{{ agent_cluster|safe }}</script>
<script type="application/json" id="agent_clusters">{{ agent_clusters|safe }}</script>